# Test

## Test Login
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "username": "edit2@test.com",
    "password": "password"
}
### 

GET http://localhost:3001/api/pages/5
###

PUT http://localhost:3001/api/pages/5
Content-Type: application/json
Cookie: connect.sid=s%3AxuAAGeFukwgepz_jl_0N7uj2lSqFVMhq.kcarR5MfpLchHF9YxHoLxkyRCJyJilNX7RH9Aht%2BBRs

{
  "id": 5,
  "title": "Page Title from swagger upd",
  "author": 3
}
###

## Delete block from page
DELETE http://localhost:3001/api/pages/5/block/11
Content-Type: application/json
Cookie: connect.sid=s%3AsBk5K1FMrpcVYE1GxIgxF4iJOOzAbmnm.pTy8BHi2dLPeKSyupacwSoMQO%2B0v8BTO3KkU5BS4z6Q
###

DELETE http://localhost:3001/api/pages/5/block/9
Content-Type: application/json
Cookie: connect.sid=s%3AsBk5K1FMrpcVYE1GxIgxF4iJOOzAbmnm.pTy8BHi2dLPeKSyupacwSoMQO%2B0v8BTO3KkU5BS4z6Q